[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][ValidateSet('Validate','Prepare','Seal')][string]$Mode,
    [Parameter(Mandatory=$true)][string]$VaultRoot,
    [string]$OverlayRoot,[string]$InputPath,[string]$OutputPath,[string]$PythonExecutable,
    [string]$ExpectedA1Hash,[string]$ExpectedA1RHash,[string]$ExpectedA1R2Hash,[string]$ExpectedA1R3Hash,[string]$ExpectedA1R4Hash,[string]$ExpectedA1R5RHash,
    [string]$ExpectedBHash,[string]$ExpectedSealInputsHash,
    [switch]$AllowSealCreation,[switch]$Json
)

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
Import-Module Microsoft.PowerShell.Management -RequiredVersion 3.1.0.0 -Force
Import-Module Microsoft.PowerShell.Utility -RequiredVersion 3.1.0.0 -Force
if([string]::IsNullOrWhiteSpace($OverlayRoot)){$OverlayRoot=Join-Path $PSScriptRoot '..'}
Import-Module (Join-Path $OverlayRoot 'tools/g3e2r-a1r5r-guard-lib.psm1') -Force
$context=Get-G3E2RA1R5RContext -VaultRoot $VaultRoot -OverlayRoot $OverlayRoot -ExpectedA1Hash $ExpectedA1Hash -ExpectedA1RHash $ExpectedA1RHash -ExpectedA1R2Hash $ExpectedA1R2Hash -ExpectedA1R3Hash $ExpectedA1R3Hash -ExpectedA1R4Hash $ExpectedA1R4Hash -ExpectedA1R5RHash $ExpectedA1R5RHash
$importReceipt=Initialize-G3E2RA1R5REntrypoint -Context $context -ComponentId 'C20-FINALIZER'
$powerShell=(Get-Process -Id $PID).Path

function Invoke-BoundPowerShell{param([string]$Script,[string[]]$Arguments,[int]$Timeout=300);return Invoke-G3E2RBoundProcess -FilePath $powerShell -ArgumentList (@('-NoProfile','-ExecutionPolicy','Bypass','-File',$Script)+$Arguments) -TimeoutSeconds $Timeout -WorkingDirectory $context.Root}
function Invoke-SnapshotGate{param([string]$Command,[object]$Seal);$selection=Resolve-G3E2RA1R5RInRoot $context.Root (Get-G3E2RA1R5RArtifact $Seal 'B-SNAPSHOT-SELECTION').repository_path;$envelope=Resolve-G3E2RA1R5RInRoot $context.Root (Get-G3E2RA1R5RArtifact $Seal 'B-SNAPSHOT-ENVELOPE').repository_path;$tool=Resolve-G3E2RA1R5RInRoot $context.Root (Get-G3E2RA1R5RExecutionPaths)['A-SNAPSHOT-TOOL'];return Invoke-BoundPowerShell $tool @('-Command',$Command,'-VaultRoot',$context.Root,'-SelectionManifest',$selection,'-SnapshotDirectory',(Split-Path -Parent $envelope))}
function Test-ComponentPrestate{$path=Resolve-G3E2RA1R5RInRoot $context.Root (Get-G3E2RA1R5RExecutionPaths)['A-COMPONENT-MANIFEST'];$rows=@(Import-Csv -LiteralPath $path);if($rows.Count-ne 95-or-not(Test-G3E2RA1R5ROrdinalUnique @($rows.move_id))){throw 'Component manifest must contain 95 ordinal-unique rows.'};foreach($row in $rows){$source=Resolve-G3E2RA1R5RInRoot $context.Root ([string]$row.source_path);$target=Resolve-G3E2RA1R5RInRoot $context.Root ([string]$row.target_path);if(-not(Test-Path -LiteralPath $source -PathType Leaf)-or(Get-G3E2RA1R5RSha256 $source)-cne$row.pre_sha256-or(Get-G3E2RA1R5RBytes $source)-ne[int64]$row.pre_bytes-or(Test-Path -LiteralPath $target)){throw "Component prestate mismatch: $($row.move_id)"}}}
function Invoke-WrapperCheck{param([object[]]$Runtimes);$python=[string](@($Runtimes|Where-Object runtime_id -CEQ 'PYTHON_AGENT')[0].executable_path);$tool=Resolve-G3E2RA1R5RInRoot $context.Root (Get-G3E2RA1R5RExecutionPaths)['A-WRAPPER-TOOL'];$manifest=$context.TransitionManifest;$null=Invoke-G3E2RBoundProcess -FilePath $python -ArgumentList @($tool,'--vault-root',$context.Root,'--manifest',$manifest,'--mode','check','--state','pre') -TimeoutSeconds 90 -WorkingDirectory $context.Root}
function Invoke-RootAndMos{$rootFast=Invoke-BoundPowerShell (Join-Path $context.Root 'tools/test-wiki-integrity.ps1') @('-Profile','Fast');if($rootFast.StdOut-notmatch'(?im)0\s+errors?'-or$rootFast.StdOut-notmatch'(?im)0\s+warnings?'){throw 'Root Fast does not prove 0/0.'};$mos=Invoke-BoundPowerShell (Join-Path $context.Root 'projects/marketing-operating-system/tools/test-federation-contracts.ps1') @() 180;if($mos.StdOut-notmatch'(?im)16/16'){throw 'MOS does not prove 16/16.'}}
function Invoke-SealPreflight{param([object]$Seal,[object[]]$Runtimes);Test-ComponentPrestate;Invoke-WrapperCheck $Runtimes;foreach($command in @('VerifyBundle','CheckLivePreState','CheckFunctionalPrestate','RestorePlan')){$null=Invoke-SnapshotGate $command $Seal};Test-G3E2RA1R5RWorkspaceAdvisory $context $Seal;$null=Test-G3E2RA1R5RLiveInvariants $context $Seal pre;$git=[string](@($Runtimes|Where-Object runtime_id -CEQ 'GIT')[0].executable_path);$rg=[string](@($Runtimes|Where-Object runtime_id -CEQ 'RIPGREP')[0].executable_path);Assert-G3E2RA1R5RGitStagingEmpty $context.Root $git;Assert-G3E2RA1R5RNoResidue $context.Root;Test-G3E2RA1R5RHardReferences $context $Seal pre $rg;Invoke-RootAndMos}
function Write-ExclusiveUtf8{param([string]$LiteralPath,[string]$Text);$parent=Split-Path -Parent $LiteralPath;if(-not(Test-Path -LiteralPath $parent -PathType Container)){throw "Seal output parent is missing: $parent"};$bytes=[Text.UTF8Encoding]::new($false).GetBytes($Text);$stream=[IO.File]::Open($LiteralPath,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None);try{$stream.Write($bytes,0,$bytes.Length);$stream.Flush($true)}finally{$stream.Dispose()}}

if($Mode-ceq'Validate'){$result=[ordered]@{contract='g3e2r-live-seal-finalizer/a1r5r';verdict='PASS';mode='Validate';state_effect='none';detached_input=$true;bundles=10;executions=63;artifacts=15;runtimes=4;ttl_seconds=900;future_skew_seconds=60;expected_hash_boundaries=9;fingerprint='ordinal-v3';json_time='invariant-parseexact-utc';import_receipt=$importReceipt.receipt_id}}
else{
    foreach($value in @($InputPath,$PythonExecutable,$ExpectedA1Hash,$ExpectedA1RHash,$ExpectedA1R2Hash,$ExpectedA1R3Hash,$ExpectedA1R4Hash,$ExpectedA1R5RHash,$ExpectedBHash,$ExpectedSealInputsHash)){if([string]::IsNullOrWhiteSpace([string]$value)){throw "$Mode requires all eight pre-seal expected hashes and the runtime path."}}
    $bState=Test-G3E2RA1R5RBManifest $context $ExpectedBHash;$resolvedInput=[IO.Path]::GetFullPath($InputPath);$requiredInput=Join-Path $bState.Root 'seal/seal-inputs.json'
    if($resolvedInput-cne$requiredInput-or(Get-G3E2RA1R5RSha256 $resolvedInput)-cne$ExpectedSealInputsHash.ToUpperInvariant()){throw 'Expected-Seal-Inputs-Hash or canonical input path mismatch.'}
    $input=Read-G3E2RA1R5RSealInputDocument $context $resolvedInput;$runtimes=Get-G3E2RA1R5RRuntimeBindings $context $PythonExecutable;$seal=New-G3E2RA1R5RSeal $context $input $runtimes $bState;Assert-G3E2RA1R5RSealClosure $context $seal -AllowPreparedB
    if($Mode-ceq'Prepare'){Invoke-SealPreflight $seal $runtimes;$result=[ordered]@{contract='g3e2r-live-seal-finalizer/a1r5r';verdict='PREPARED_READ_ONLY';mode='Prepare';state_effect='none';expected_a1_hash=$ExpectedA1Hash.ToUpperInvariant();expected_a1r_hash=$ExpectedA1RHash.ToUpperInvariant();expected_a1r2_hash=$ExpectedA1R2Hash.ToUpperInvariant();expected_a1r3_hash=$ExpectedA1R3Hash.ToUpperInvariant();expected_a1r4_hash=$ExpectedA1R4Hash.ToUpperInvariant();expected_a1r5r_hash=$ExpectedA1R5RHash.ToUpperInvariant();expected_b_hash=$ExpectedBHash.ToUpperInvariant();expected_seal_inputs_hash=$ExpectedSealInputsHash.ToUpperInvariant();import_receipt=$importReceipt.receipt_id}}
    else{
        if(-not$AllowSealCreation-or-not(Test-G3E2RA1R5RAdministrator)){throw 'Seal mode requires explicit creation authority and one elevated runner.'};foreach($field in @('live_capability_probe_approved','live_mutation_approved','automatic_reverse_approved','independent_reverse_approved')){if(-not[bool]$input.Value.approval.$field){throw "Seal approval is missing: $field"}}
        $resolvedOutput=[IO.Path]::GetFullPath($OutputPath);if($resolvedOutput-cne(Join-Path $bState.Root 'live-seal-v2.json')-or(Test-Path -LiteralPath $resolvedOutput)){throw 'Seal output must be the absent canonical live-seal-v2.json.'}
        $mutex=$null;$lock=$null;$created=$null
        try{$mutex=Enter-G3E2RA1R5RMutex $context.Root;Invoke-SealPreflight $seal $runtimes;if((Get-G3E2RA1R5RSha256 $context.A1R2Context.A1RContext.A1Manifest)-cne$ExpectedA1Hash.ToUpperInvariant()-or(Get-G3E2RA1R5RSha256 $context.A1R2Context.A1RManifest)-cne$ExpectedA1RHash.ToUpperInvariant()-or(Get-G3E2RA1R5RSha256 $context.A1R2Manifest)-cne$ExpectedA1R2Hash.ToUpperInvariant()-or(Get-G3E2RA1R5RSha256 $context.A1R3Manifest)-cne$ExpectedA1R3Hash.ToUpperInvariant()-or(Get-G3E2RA1R5RSha256 $context.A1R4Manifest)-cne$ExpectedA1R4Hash.ToUpperInvariant()-or(Get-G3E2RA1R5RSha256 $context.Manifest)-cne$ExpectedA1R5RHash.ToUpperInvariant()-or(Get-G3E2RA1R5RSha256 $bState.Manifest)-cne$ExpectedBHash.ToUpperInvariant()-or(Get-G3E2RA1R5RSha256 $resolvedInput)-cne$ExpectedSealInputsHash.ToUpperInvariant()){throw 'Final eight pre-seal Expected-Hash boundaries failed.'};$lock=Enter-G3E2RA1R5RClosureLock $context $seal;Test-G3E2RA1R5RClosureLock $lock;$seal=Complete-G3E2RA1R5RSealTimes $seal ([DateTimeOffset]::UtcNow);Write-ExclusiveUtf8 $resolvedOutput (($seal|ConvertTo-Json -Depth 16)+[Environment]::NewLine);$created=Get-G3E2RA1R5RSha256 $resolvedOutput;$null=Test-G3E2RA1R5RBManifest $context $ExpectedBHash -AllowSealed;$result=[ordered]@{contract='g3e2r-live-seal-finalizer/a1r5r';verdict='SEALED_ROUTING_FROZEN';mode='Seal';state_effect='new-live-seal-only';expected_seal_hash=$created;not_after_utc=$seal.time.not_after_utc}}
        catch{if($null-ne$created-and(Test-Path -LiteralPath $resolvedOutput)-and(Get-G3E2RA1R5RSha256 $resolvedOutput)-ceq$created){[IO.File]::Delete($resolvedOutput)};throw}finally{Exit-G3E2RA1R5RClosureLock $lock;if($null-ne$mutex){Exit-G3E2RA1R5RMutex $mutex}}
    }
}
if($Json){$result|ConvertTo-Json -Depth 8 -Compress}else{Write-Output "$($result.verdict) | mode=$Mode | routing frozen"}
