[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][ValidateSet('Validate','Prepare','Seal')][string]$Mode,
    [Parameter(Mandatory=$true)][string]$VaultRoot,
    [string]$OverlayRoot,[string]$InputPath,[string]$OutputPath,[string]$PythonExecutable,
    [string]$ExpectedA1Hash,[string]$ExpectedA1RHash,[string]$ExpectedA1R2Hash,
    [string]$ExpectedBHash,[string]$ExpectedSealInputsHash,
    [switch]$AllowSealCreation,[switch]$Json
)

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
if([string]::IsNullOrWhiteSpace($OverlayRoot)){$OverlayRoot=Join-Path $PSScriptRoot '..'}
Import-Module (Join-Path $OverlayRoot 'tools/g3e2r-a1r2-guard-lib.psm1') -Force
$context=Get-G3E2RA1R2Context -VaultRoot $VaultRoot -OverlayRoot $OverlayRoot -ExpectedA1Hash $ExpectedA1Hash -ExpectedA1RHash $ExpectedA1RHash -ExpectedA1R2Hash $ExpectedA1R2Hash
Import-Module (Join-Path $context.A1RContext.A1Context.ARoot 'tools/g3e2r-transaction-lib.psm1') -Force
$powerShell=(Get-Process -Id $PID).Path

function Invoke-BoundPowerShell{param([string]$Script,[string[]]$Arguments,[int]$Timeout=300);return Invoke-G3E2RBoundProcess -FilePath $powerShell -ArgumentList (@('-NoProfile','-ExecutionPolicy','Bypass','-File',$Script)+$Arguments) -TimeoutSeconds $Timeout -WorkingDirectory $context.Root}
function Invoke-SnapshotGate{param([string]$Command,[object]$Seal);$selection=Resolve-G3E2RA1R2InRoot $context.Root (Get-G3E2RA1R2Artifact $Seal 'B-SNAPSHOT-SELECTION').repository_path;$envelope=Resolve-G3E2RA1R2InRoot $context.Root (Get-G3E2RA1R2Artifact $Seal 'B-SNAPSHOT-ENVELOPE').repository_path;$tool=Resolve-G3E2RA1R2InRoot $context.Root (Get-G3E2RA1R2ExecutionPaths)['A-SNAPSHOT-TOOL'];return Invoke-BoundPowerShell $tool @('-Command',$Command,'-VaultRoot',$context.Root,'-SelectionManifest',$selection,'-SnapshotDirectory',(Split-Path -Parent $envelope))}
function Test-ComponentPrestate{$path=Resolve-G3E2RA1R2InRoot $context.Root (Get-G3E2RA1R2ExecutionPaths)['A-COMPONENT-MANIFEST'];$rows=@(Import-Csv -LiteralPath $path);if($rows.Count-ne 95-or@($rows.move_id|Sort-Object -Unique).Count-ne 95){throw 'Component manifest must contain 95 unique rows.'};foreach($row in $rows){$source=Resolve-G3E2RA1R2InRoot $context.Root ([string]$row.source_path);$target=Resolve-G3E2RA1R2InRoot $context.Root ([string]$row.target_path);if(-not(Test-Path -LiteralPath $source -PathType Leaf)-or(Get-G3E2RA1R2Sha256 $source)-cne$row.pre_sha256-or(Get-G3E2RA1R2Bytes $source)-ne[int64]$row.pre_bytes-or(Test-Path -LiteralPath $target)){throw "Component prestate mismatch: $($row.move_id)"}}}
function Invoke-WrapperCheck{param([object[]]$Runtimes);$python=[string](@($Runtimes|Where-Object runtime_id -CEQ 'PYTHON_AGENT')[0].executable_path);$tool=Resolve-G3E2RA1R2InRoot $context.Root (Get-G3E2RA1R2ExecutionPaths)['A-WRAPPER-TOOL'];$manifest=$context.TransitionManifest;$null=Invoke-G3E2RBoundProcess -FilePath $python -ArgumentList @($tool,'--vault-root',$context.Root,'--manifest',$manifest,'--mode','check','--state','pre') -TimeoutSeconds 90 -WorkingDirectory $context.Root}
function Invoke-RootAndMos{$rootFast=Invoke-BoundPowerShell (Join-Path $context.Root 'tools/test-wiki-integrity.ps1') @('-Profile','Fast');if($rootFast.StdOut-notmatch'(?im)0\s+errors?'-or$rootFast.StdOut-notmatch'(?im)0\s+warnings?'){throw 'Root Fast does not prove 0/0.'};$mos=Invoke-BoundPowerShell (Join-Path $context.Root 'projects/marketing-operating-system/tools/test-federation-contracts.ps1') @() 180;if($mos.StdOut-notmatch'(?im)16/16'){throw 'MOS does not prove 16/16.'}}
function Invoke-SealPreflight{param([object]$Seal,[object[]]$Runtimes);Test-ComponentPrestate;Invoke-WrapperCheck $Runtimes;foreach($command in @('VerifyBundle','CheckLivePreState','CheckFunctionalPrestate','RestorePlan')){$null=Invoke-SnapshotGate $command $Seal};Test-G3E2RA1R2WorkspaceAdvisory $context $Seal;$null=Test-G3E2RA1R2LiveInvariants $context $Seal pre;$git=[string](@($Runtimes|Where-Object runtime_id -CEQ 'GIT')[0].executable_path);$rg=[string](@($Runtimes|Where-Object runtime_id -CEQ 'RIPGREP')[0].executable_path);Assert-G3E2RA1R2GitStagingEmpty $context.Root $git;Assert-G3E2RA1R2NoResidue $context.Root;Test-G3E2RA1R2HardReferences $context $Seal pre $rg;Invoke-RootAndMos}
function Write-ExclusiveUtf8{param([string]$LiteralPath,[string]$Text);$parent=Split-Path -Parent $LiteralPath;if(-not(Test-Path -LiteralPath $parent -PathType Container)){throw "Seal output parent is missing: $parent"};$bytes=[Text.UTF8Encoding]::new($false).GetBytes($Text);$stream=[IO.File]::Open($LiteralPath,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None);try{$stream.Write($bytes,0,$bytes.Length);$stream.Flush($true)}finally{$stream.Dispose()}}

if($Mode-ceq'Validate'){$result=[ordered]@{contract='g3e2r-live-seal-finalizer/a1r2';verdict='PASS';mode='Validate';state_effect='none';detached_input=$true;bundles=7;executions=36;artifacts=15;runtimes=4;ttl_seconds=900;expected_hash_boundaries=6}}
else{
    foreach($value in @($InputPath,$PythonExecutable,$ExpectedA1Hash,$ExpectedA1RHash,$ExpectedA1R2Hash,$ExpectedBHash,$ExpectedSealInputsHash)){if([string]::IsNullOrWhiteSpace([string]$value)){throw "$Mode requires all five pre-seal expected hashes and the runtime path."}}
    $bState=Test-G3E2RA1R2BManifest $context $ExpectedBHash;$resolvedInput=[IO.Path]::GetFullPath($InputPath);$requiredInput=Join-Path $bState.Root 'seal/seal-inputs.json'
    if($resolvedInput-cne$requiredInput-or(Get-G3E2RA1R2Sha256 $resolvedInput)-cne$ExpectedSealInputsHash.ToUpperInvariant()){throw 'Expected-Seal-Inputs-Hash or canonical input path mismatch.'}
    $input=Get-Content -LiteralPath $resolvedInput -Raw -Encoding UTF8|ConvertFrom-Json;Assert-G3E2RA1R2SealInput $context $input;$runtimes=Get-G3E2RA1R2RuntimeBindings $context $PythonExecutable;$seal=New-G3E2RA1R2Seal $context $input $runtimes $bState;Assert-G3E2RA1R2SealClosure $context $seal -AllowPreparedB
    if($Mode-ceq'Prepare'){Invoke-SealPreflight $seal $runtimes;$result=[ordered]@{contract='g3e2r-live-seal-finalizer/a1r2';verdict='PREPARED_READ_ONLY';mode='Prepare';state_effect='none';expected_a1_hash=$ExpectedA1Hash.ToUpperInvariant();expected_a1r_hash=$ExpectedA1RHash.ToUpperInvariant();expected_a1r2_hash=$ExpectedA1R2Hash.ToUpperInvariant();expected_b_hash=$ExpectedBHash.ToUpperInvariant();expected_seal_inputs_hash=$ExpectedSealInputsHash.ToUpperInvariant()}}
    else{
        if(-not$AllowSealCreation-or-not(Test-G3E2RA1R2Administrator)){throw 'Seal mode requires explicit creation authority and one elevated runner.'};foreach($field in @('live_capability_probe_approved','live_mutation_approved','automatic_reverse_approved','independent_reverse_approved')){if(-not[bool]$input.approval.$field){throw "Seal approval is missing: $field"}}
        $resolvedOutput=[IO.Path]::GetFullPath($OutputPath);if($resolvedOutput-cne(Join-Path $bState.Root 'live-seal-v2.json')-or(Test-Path -LiteralPath $resolvedOutput)){throw 'Seal output must be the absent canonical live-seal-v2.json.'}
        $mutex=$null;$lock=$null;$created=$null
        try{$mutex=Enter-G3E2RA1R2Mutex $context.Root;Invoke-SealPreflight $seal $runtimes;if((Get-G3E2RA1R2Sha256 $context.A1RContext.A1Manifest)-cne$ExpectedA1Hash.ToUpperInvariant()-or(Get-G3E2RA1R2Sha256 $context.A1RManifest)-cne$ExpectedA1RHash.ToUpperInvariant()-or(Get-G3E2RA1R2Sha256 $context.Manifest)-cne$ExpectedA1R2Hash.ToUpperInvariant()-or(Get-G3E2RA1R2Sha256 $bState.Manifest)-cne$ExpectedBHash.ToUpperInvariant()-or(Get-G3E2RA1R2Sha256 $resolvedInput)-cne$ExpectedSealInputsHash.ToUpperInvariant()){throw 'Final five pre-seal Expected-Hash boundaries failed.'};$lock=Enter-G3E2RA1R2ClosureLock $context $seal;Test-G3E2RA1R2ClosureLock $lock;$now=[DateTimeOffset]::UtcNow;$seal.time.sealed_at_utc=$now.ToString('o');$seal.time.not_after_utc=$now.AddSeconds(900).ToString('o');Write-ExclusiveUtf8 $resolvedOutput (($seal|ConvertTo-Json -Depth 16)+[Environment]::NewLine);$created=Get-G3E2RA1R2Sha256 $resolvedOutput;$null=Test-G3E2RA1R2BManifest $context $ExpectedBHash -AllowSealed;$result=[ordered]@{contract='g3e2r-live-seal-finalizer/a1r2';verdict='SEALED_ROUTING_FROZEN';mode='Seal';state_effect='new-live-seal-only';expected_seal_hash=$created;not_after_utc=$seal.time.not_after_utc}}
        catch{if($null-ne$created-and(Test-Path -LiteralPath $resolvedOutput)-and(Get-G3E2RA1R2Sha256 $resolvedOutput)-ceq$created){[IO.File]::Delete($resolvedOutput)};throw}finally{Exit-G3E2RA1R2ClosureLock $lock;if($null-ne$mutex){Exit-G3E2RA1R2Mutex $mutex}}
    }
}
if($Json){$result|ConvertTo-Json -Depth 8 -Compress}else{Write-Output "$($result.verdict) | mode=$Mode | routing frozen"}
