[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][ValidateSet('Validate','Simulate','Apply')][string]$Mode,
    [Parameter(Mandatory=$true)][string]$VaultRoot,[string]$OverlayRoot,[string]$SealEnvelope,
    [string]$PythonExecutable,[string]$FailAtStep,[string]$ExpectedA1Hash,[string]$ExpectedA1RHash,
    [string]$ExpectedA1R2Hash,[string]$ExpectedSealHash,
    [switch]$AllowLiveMutation,[switch]$AllowAutomaticReverse,[switch]$AllowCapabilityProbe,[switch]$Json
)
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop'
if([string]::IsNullOrWhiteSpace($OverlayRoot)){$OverlayRoot=Join-Path $PSScriptRoot '..'}
Import-Module (Join-Path $OverlayRoot 'tools/g3e2r-a1r2-guard-lib.psm1') -Force
$context=Get-G3E2RA1R2Context -VaultRoot $VaultRoot -OverlayRoot $OverlayRoot -ExpectedA1Hash $ExpectedA1Hash -ExpectedA1RHash $ExpectedA1RHash -ExpectedA1R2Hash $ExpectedA1R2Hash
Import-Module (Join-Path $context.A1RContext.A1Context.ARoot 'tools/g3e2r-transaction-lib.psm1') -Force
$root=$context.Root;$paths=Get-G3E2RA1R2ExecutionPaths;$powerShell=(Get-Process -Id $PID).Path
$componentPath=Resolve-G3E2RA1R2InRoot $root $paths['A-COMPONENT-MANIFEST'];$forwardPath=Resolve-G3E2RA1R2InRoot $root $paths['A-FORWARD-MANIFEST'];$reversePath=Resolve-G3E2RA1R2InRoot $root $paths['A-REVERSE-MANIFEST'];$snapshotTool=Resolve-G3E2RA1R2InRoot $root $paths['A-SNAPSHOT-TOOL'];$wrapperTool=Resolve-G3E2RA1R2InRoot $root $paths['A-WRAPPER-TOOL'];$reverseTool=Join-Path $context.Overlay 'tools/invoke-g3e2-reverse-a1r2.ps1'

function Get-StaticState{$components=@(Import-Csv -LiteralPath $componentPath);if($components.Count-ne 95-or@($components.move_id|Sort-Object -Unique).Count-ne 95-or@($components|Where-Object identity_state -CEQ 'byte-identical').Count-ne 74-or@($components|Where-Object identity_state -CEQ 'reviewed-refactor-candidate').Count-ne 21){throw 'Component transition must contain the exact 95-row 74/21 split.'};$forward=Import-G3E2RTransactionManifest -LiteralPath $forwardPath -Prefix FWD -ExpectedCount 19;$reverse=Import-G3E2RTransactionManifest -LiteralPath $reversePath -Prefix REV -ExpectedCount 12;return [pscustomobject]@{Components=$components;Forward=$forward;Reverse=$reverse}}
function Assert-ComponentPrestate{param([object[]]$Rows);foreach($row in $Rows){$source=Resolve-G3E2RA1R2InRoot $root ([string]$row.source_path) -ForMutation;$target=Resolve-G3E2RA1R2InRoot $root ([string]$row.target_path) -ForMutation;if(-not(Test-Path -LiteralPath $source -PathType Leaf)-or(Get-G3E2RA1R2Sha256 $source)-cne$row.pre_sha256-or(Get-G3E2RA1R2Bytes $source)-ne[int64]$row.pre_bytes-or(Test-Path -LiteralPath $target)){throw "Component prestate mismatch: $($row.move_id)"}}}
function Assert-ComponentPoststate{param([object[]]$Rows);foreach($row in $Rows){$source=Resolve-G3E2RA1R2InRoot $root $row.source_path;$target=Resolve-G3E2RA1R2InRoot $root $row.target_path;if(Test-Path -LiteralPath $source){throw "Component source remains: $($row.source_path)"};if(-not(Test-Path -LiteralPath $target -PathType Leaf)-or(Get-G3E2RA1R2Sha256 $target)-cne$row.post_sha256){throw "Component poststate mismatch: $($row.move_id)"}}}
function Move-Components{param([object[]]$Rows);foreach($row in $Rows){$source=Resolve-G3E2RA1R2InRoot $root ([string]$row.source_path) -ForMutation;$target=Resolve-G3E2RA1R2InRoot $root ([string]$row.target_path) -ForMutation;$parent=Split-Path -Parent $target;if(-not(Test-Path -LiteralPath $parent -PathType Container)){$null=New-Item -ItemType Directory -Path $parent -Force};[IO.File]::Move($source,$target)}}
function Invoke-BoundPowerShell{param([string]$Script,[string[]]$Arguments,[int]$Timeout=300);return Invoke-G3E2RBoundProcess -FilePath $powerShell -ArgumentList (@('-NoProfile','-ExecutionPolicy','Bypass','-File',$Script)+$Arguments) -TimeoutSeconds $Timeout -WorkingDirectory $root}
function Invoke-RootFast{$r=Invoke-BoundPowerShell (Join-Path $root 'tools/test-wiki-integrity.ps1') @('-Profile','Fast');if($r.StdOut-notmatch'(?im)0\s+errors?'-or$r.StdOut-notmatch'(?im)0\s+warnings?'){throw 'Root Fast does not prove 0/0.'}}
function Invoke-MosRegression{$r=Invoke-BoundPowerShell (Join-Path $root 'projects/marketing-operating-system/tools/test-federation-contracts.ps1') @() 180;if($r.StdOut-notmatch'(?im)16/16'){throw 'MOS does not prove 16/16.'}}
function Invoke-Snapshot{param([string]$Command,[object]$Seal);$selection=Resolve-G3E2RA1R2InRoot $root (Get-G3E2RA1R2Artifact $Seal 'B-SNAPSHOT-SELECTION').repository_path;$envelope=Resolve-G3E2RA1R2InRoot $root (Get-G3E2RA1R2Artifact $Seal 'B-SNAPSHOT-ENVELOPE').repository_path;return Invoke-BoundPowerShell $snapshotTool @('-Command',$Command,'-VaultRoot',$root,'-SelectionManifest',$selection,'-SnapshotDirectory',(Split-Path -Parent $envelope))}
function Invoke-Wrapper{param([ValidateSet('check','capability-probe','apply')][string]$ModeName,[ValidateSet('pre','post')][string]$State,[object[]]$Runtimes);$python=[string](@($Runtimes|Where-Object runtime_id -CEQ 'PYTHON_AGENT')[0].executable_path);return Invoke-G3E2RBoundProcess -FilePath $python -ArgumentList @($wrapperTool,'--vault-root',$root,'--manifest',$context.TransitionManifest,'--mode',$ModeName,'--state',$State) -TimeoutSeconds 90 -WorkingDirectory $root}
function Assert-SealArtifacts{param([object]$Seal);foreach($id in @($context.SealContract.required_artifact_binding_ids)){$null=Test-G3E2RA1R2BoundArtifact $context (Get-G3E2RA1R2Artifact $Seal $id)}}
function Invoke-PreMutationChecks{param([object]$Seal,[object[]]$Runtimes,[object[]]$Components,[switch]$CapabilityProbe);$b=@($Seal.bundle_bindings|Where-Object bundle_id -CEQ 'G3E2R-B-BUNDLE')[0];$null=Test-G3E2RA1R2BManifest $context ([string]$b.sha256) -AllowSealed;Assert-G3E2RA1R2SealClosure $context $Seal;Assert-SealArtifacts $Seal;Assert-ComponentPrestate $Components;$git=[string](@($Runtimes|Where-Object runtime_id -CEQ 'GIT')[0].executable_path);$rg=[string](@($Runtimes|Where-Object runtime_id -CEQ 'RIPGREP')[0].executable_path);Assert-G3E2RA1R2GitStagingEmpty $root $git;Assert-G3E2RA1R2NoResidue $root;$null=Test-G3E2RA1R2LiveInvariants $context $Seal pre;$null=Invoke-Wrapper check pre $Runtimes;if($CapabilityProbe){$null=Invoke-Wrapper capability-probe pre $Runtimes;Assert-G3E2RA1R2NoResidue $root;$null=Test-G3E2RA1R2LiveInvariants $context $Seal pre};foreach($command in @('VerifyBundle','CheckLivePreState','CheckFunctionalPrestate','RestorePlan')){$null=Invoke-Snapshot $command $Seal};Test-G3E2RA1R2WorkspaceAdvisory $context $Seal;Test-G3E2RA1R2HardReferences $context $Seal pre $rg;Invoke-MosRegression;Invoke-RootFast;Assert-G3E2RA1R2GitStagingEmpty $root $git;Assert-G3E2RA1R2NoResidue $root}

$static=Get-StaticState
if($Mode-ceq'Validate'){$result=[ordered]@{contract='g3e2r-transaction/a1r2';verdict='PASS';mode='Validate';components=95;forward=19;reverse=12;wrapper_inventory='dynamic-full-tree';immediate_boundary='complete';authority_effect='none'}}
elseif($Mode-ceq'Simulate'){
    if(-not[string]::IsNullOrWhiteSpace($FailAtStep)-and$FailAtStep-notin@($static.Forward.step_id)){throw "Unknown simulation failure step: $FailAtStep"};$mutationStarted=$false;$completed=[Collections.Generic.List[string]]::new();foreach($step in $static.Forward){if([int]$step.sequence-ge 10){$mutationStarted=$true};if($step.step_id-ceq$FailAtStep){break};$completed.Add([string]$step.step_id)}
    if([string]::IsNullOrWhiteSpace($FailAtStep)){$result=[ordered]@{contract='g3e2r-transaction/a1r2';verdict='PASS_ROUTING_FROZEN';mode='Simulate';completed=@($completed);reverse_invoked=$false;authority_effect='none'}}elseif(-not$mutationStarted){$result=[ordered]@{contract='g3e2r-transaction/a1r2';verdict='HOLD_NO_MUTATION';mode='Simulate';failed_step=$FailAtStep;completed=@($completed);reverse_invoked=$false;authority_effect='none'}}else{$reverse=&$reverseTool -Mode Simulate -VaultRoot $root -OverlayRoot $context.Overlay -ExpectedA1Hash $ExpectedA1Hash -ExpectedA1RHash $ExpectedA1RHash -ExpectedA1R2Hash $ExpectedA1R2Hash -Json|ConvertFrom-Json;if($reverse.verdict-cne'REVERSED_ROUTING_FROZEN'-or@($reverse.completed).Count-ne 12){throw 'A1R2 reverse simulation failed.'};$result=[ordered]@{contract='g3e2r-transaction/a1r2';verdict='REVERSED_ROUTING_FROZEN';mode='Simulate';failed_step=$FailAtStep;completed=@($completed);reverse_invoked=$true;reverse_steps=@($reverse.completed);authority_effect='none'}}
}
else{
    if(-not$AllowLiveMutation-or-not$AllowAutomaticReverse-or-not$AllowCapabilityProbe-or-not(Test-G3E2RA1R2Administrator)){throw 'Apply requires all three explicit authorities and one elevated runner.'};foreach($v in @($SealEnvelope,$PythonExecutable,$ExpectedA1Hash,$ExpectedA1RHash,$ExpectedA1R2Hash,$ExpectedSealHash)){if([string]::IsNullOrWhiteSpace([string]$v)){throw 'Apply requires all expected hashes, seal, and runtime.'}}
    $mutex=$null;$lock=$null;$mutationStarted=$false;$mutexReleased=$false
    try{$mutex=Enter-G3E2RA1R2Mutex $root;$sealPath=[IO.Path]::GetFullPath($SealEnvelope);if(-not$sealPath.StartsWith($root+'\',[StringComparison]::OrdinalIgnoreCase)){throw 'Live seal must remain inside the Vault.'};$runtimes=Get-G3E2RA1R2RuntimeBindings $context $PythonExecutable;$seal=Read-G3E2RA1R2Seal $context $sealPath $ExpectedA1Hash $ExpectedA1RHash $ExpectedA1R2Hash $ExpectedSealHash $runtimes Forward;$seal=Add-G3E2RA1R2CompatibilityProperties $seal;Invoke-PreMutationChecks $seal $runtimes $static.Components -CapabilityProbe;$lock=Enter-G3E2RA1R2ClosureLock $context $seal $sealPath $ExpectedSealHash;Invoke-PreMutationChecks $seal $runtimes $static.Components;$null=Read-G3E2RA1R2Seal $context $sealPath $ExpectedA1Hash $ExpectedA1RHash $ExpectedA1R2Hash $ExpectedSealHash $runtimes Forward;Test-G3E2RA1R2ClosureLock $lock;$mutationStarted=$true;Move-Components $static.Components
        $componentTool=(Get-G3E2RDependency -Lock $context.A1RContext.ADependencies -Id 'G3E1-APPLY-COMPONENT').Path;$null=Invoke-BoundPowerShell $componentTool @('-Mode','Apply','-VaultRoot',$root,'-MoveManifest',(Get-G3E2RDependency -Lock $context.A1RContext.ADependencies -Id 'G3E1-MOVE').Path,'-RefactorSpec',(Get-G3E2RDependency -Lock $context.A1RContext.ADependencies -Id 'G3E1-REFACTOR-SPEC').Path,'-PostHashManifest',(Get-G3E2RDependency -Lock $context.A1RContext.ADependencies -Id 'G3E1-COMPONENT-POST').Path) 180
        $postTool=(Get-G3E2RDependency -Lock $context.A1RContext.ADependencies -Id 'G3E1-APPLY-POSTSTATE').Path;$postManifest=Resolve-G3E2RA1R2InRoot $root (Get-G3E2RA1R2Artifact $seal 'B-EXACT-POSTSTATE-MANIFEST').repository_path;$postArchive=Resolve-G3E2RA1R2InRoot $root (Get-G3E2RA1R2Artifact $seal 'G3E1-EXACT-POSTSTATE-ARCHIVE').repository_path;$null=Invoke-BoundPowerShell $postTool @('-Mode','Apply','-VaultRoot',$root,'-ManifestPath',$postManifest,'-ArchivePath',$postArchive) 180;$null=Invoke-Wrapper apply post $runtimes;Assert-ComponentPoststate $static.Components;$null=Invoke-BoundPowerShell $postTool @('-Mode','CheckPost','-VaultRoot',$root,'-ManifestPath',$postManifest,'-ArchivePath',$postArchive) 180;$null=Invoke-Wrapper check post $runtimes
        $rg=[string](@($runtimes|Where-Object runtime_id -CEQ 'RIPGREP')[0].executable_path);$git=[string](@($runtimes|Where-Object runtime_id -CEQ 'GIT')[0].executable_path);Test-G3E2RA1R2HardReferences $context $seal post $rg;$null=Test-G3E2RA1R2LiveInvariants $context $seal post;Assert-G3E2RA1R2GitStagingEmpty $root $git;Assert-G3E2RA1R2NoResidue $root;Invoke-MosRegression;Invoke-RootFast;$result=[ordered]@{contract='g3e2r-transaction/a1r2';verdict='PASS_ROUTING_FROZEN';mode='Apply';transaction_id=$seal.transaction_id;completed=@($static.Forward.step_id);reverse_invoked=$false;routing_state='frozen'}
    }catch{$forwardError=$_;if($mutationStarted){Exit-G3E2RA1R2ClosureLock $lock;$lock=$null;if($null-ne$mutex){Exit-G3E2RA1R2Mutex $mutex;$mutex=$null;$mutexReleased=$true};try{$null=Invoke-BoundPowerShell $reverseTool @('-Mode','Apply','-VaultRoot',$root,'-OverlayRoot',$context.Overlay,'-SealEnvelope',$sealPath,'-PythonExecutable',$PythonExecutable,'-ExpectedA1Hash',$ExpectedA1Hash,'-ExpectedA1RHash',$ExpectedA1RHash,'-ExpectedA1R2Hash',$ExpectedA1R2Hash,'-ExpectedSealHash',$ExpectedSealHash,'-AllowLiveMutation','-AllowReverse') 900}catch{throw "Forward and automatic reverse failed. Forward: $forwardError Reverse: $_"};throw "Forward failed after mutation; complete reverse passed and routing remains frozen. Cause: $forwardError"};throw $forwardError}finally{Exit-G3E2RA1R2ClosureLock $lock;if($null-ne$mutex-and-not$mutexReleased){Exit-G3E2RA1R2Mutex $mutex}}
}
if($Json){$result|ConvertTo-Json -Depth 8 -Compress}else{Write-Output "$($result.verdict) | mode=$Mode | routing frozen"}
