[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][string]$VaultRoot,[string]$OverlayRoot,
    [Parameter(Mandatory=$true)][string]$PythonExecutable,[switch]$Json
)
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop'
if([string]::IsNullOrWhiteSpace($OverlayRoot)){$OverlayRoot=Join-Path $PSScriptRoot '..'}
$root=(Resolve-Path -LiteralPath $VaultRoot).Path.TrimEnd('\');$overlay=(Resolve-Path -LiteralPath $OverlayRoot).Path.TrimEnd('\')
Import-Module (Join-Path $overlay 'tools/g3e2r-a1r2-guard-lib.psm1') -Force
$manifest=Join-Path $overlay 'a1r2-bundle-manifest.csv';$expectedA1R2=Get-G3E2RA1R2Sha256 $manifest;$expectedA1R='57DBC2BC3F91D6C201E9F7506576A9F2F07E55D17808B058E9F1933380249B2D';$expectedA1='8878AA92D1F82DB4F9B3D8E4C1F5E707F36E77E3013195ABF7AD7784AE185AC7'
$context=Get-G3E2RA1R2Context $root $overlay $expectedA1 $expectedA1R $expectedA1R2;$checks=[Collections.Generic.List[string]]::new();$powerShell=(Get-Process -Id $PID).Path
function Add-Check{param([string]$Id,[bool]$Passed,[string]$Evidence);if(-not$Passed){throw "$Id failed: $Evidence"};$checks.Add("$Id|$Evidence")}
function Expect-Failure{param([scriptblock]$Action);try{&$Action;$false}catch{$true}}
function Parse-Tool{param([string]$Path);$tokens=$null;$errors=$null;[void][Management.Automation.Language.Parser]::ParseFile($Path,[ref]$tokens,[ref]$errors);return @($errors)}
function Invoke-JsonScript{param([string]$Script,[string[]]$Arguments);$saved=$ErrorActionPreference;$ErrorActionPreference='Continue';try{$out=&$powerShell -NoProfile -ExecutionPolicy Bypass -File $Script @Arguments 2>&1;$code=$LASTEXITCODE}finally{$ErrorActionPreference=$saved};if($code-ne 0){throw "Child failed: $Script`n$($out-join[Environment]::NewLine)"};$line=@($out|ForEach-Object{[string]$_}|Where-Object{$_.TrimStart().StartsWith('{')}|Select-Object -Last 1);if($line.Count-ne 1){throw "Child returned no JSON: $Script"};return ($line[0]|ConvertFrom-Json)}
function Write-Utf8{param([string]$Path,[string]$Text);$null=[IO.Directory]::CreateDirectory((Split-Path -Parent $Path));[IO.File]::WriteAllText($Path,$Text,[Text.UTF8Encoding]::new($false))}
function Save-Csv{param([object[]]$Rows,[string]$Path);$Rows|Export-Csv -LiteralPath $Path -NoTypeInformation -Encoding UTF8}

$a1rBefore=Get-G3E2RA1R2TreeFingerprintV2 $context.A1RRoot;$a1Before=Get-G3E2RA1R2TreeFingerprintV2 $context.A1RContext.A1Root;$aBefore=Get-G3E2RA1R2TreeFingerprintV2 $context.A1RContext.A1Context.ARoot;$g3e1Before=Get-G3E2RA1R2TreeFingerprintV2 $context.A1RContext.A1Context.G3E1Root
$rows=@(Import-Csv -LiteralPath $manifest);Add-Check T01-EXACT-A1R2-INVENTORY ($rows.Count-eq 14-and@(Get-ChildItem -LiteralPath $overlay -Recurse -File).Count-eq 15) '14 bound members plus manifest'
$lock=@(Import-Csv -LiteralPath (Join-Path $overlay 'dependency-lock.csv'));Add-Check T02-ONE-LINE-A1R-LOCK ($lock.Count-eq 1-and$lock[0].dependency_id-ceq'G3E2R-A1R-BUNDLE'-and$lock[0].sha256-ceq$expectedA1R) 'one immutable A1R dependency'
Add-Check T03-A1R-EXACT-CLOSURE ((Get-G3E2RA1R2Sha256 $context.A1RManifest)-ceq$expectedA1R-and@(Import-Csv -LiteralPath $context.A1RManifest).Count-eq 14) 'accepted A1R manifest and members'
Add-Check T04-TRANSITIVE-UPSTREAM-CLOSURE ((Get-G3E2RA1R2Sha256 $context.A1RContext.A1Manifest)-ceq$expectedA1-and(Get-G3E2RA1R2Sha256 $context.A1RContext.A1Context.Dependencies['G3E2R-A-BUNDLE'])-ceq'5114660FB6968CF5979F17AC7ECC95833A69C26E5C94C633B1E955C48393C055'-and(Get-G3E2RA1R2Sha256 $context.A1RContext.A1Context.Dependencies['G3E1-BUNDLE'])-ceq'D581C9535B6359F7058DA33C3CB9E229EC8EF1C8C2C6C4D49311C75189D20E50') 'A1 A and G3E1 exact'
$sealRaw=Get-Content -LiteralPath (Join-Path $overlay 'contracts/live-seal-v2-a1r2-contract.json') -Raw;$invRaw=Get-Content -LiteralPath (Join-Path $overlay 'contracts/live-invariant-v2-contract.json') -Raw;$guardRaw=Get-Content -LiteralPath (Join-Path $overlay 'tools/g3e2r-a1r2-guard-lib.psm1') -Raw
Add-Check T05-DYNAMIC-CONTRACT-NO-GLOBAL-COUNT (-not$invRaw.Contains('"row_count": 52')-and-not$invRaw.Contains('"wrapper_file_count": 16')-and$invRaw.Contains('live-wrapper-file-count + transition-action-count')) 'wrapper and total counts are derived'
$inventory=@(Get-G3E2RA1R2WrapperInventory $context);Add-Check T06-FULL-LIVE-WRAPPER-INVENTORY ($inventory.Count-eq 16-and@($inventory.repository_path|Sort-Object -Unique).Count-eq$inventory.Count) 'current complete file inventory has sixteen unique wrappers'
$transitions=@(Get-G3E2RA1R2TransitionRows $context);Add-Check T07-UNCHANGED-TRANSITION-MANIFEST ($transitions.Count-eq 11-and(Get-G3E2RA1R2Sha256 $context.TransitionManifest)-ceq'5DA801A1CE4160181EEB098CD17EE7EFFDAADAA0AC756B543FB537B08DFC9EA1') 'eleven exact G3E1 rows'
$actions=@($transitions|Where-Object action -CEQ 'transition');$verify=@($transitions|Where-Object action -CEQ 'verify-only');Add-Check T08-TRANSITION-ACTION-SPLIT ($actions.Count-eq 10-and$verify.Count-eq 1) 'ten transition and one verify-only'
$external=@($inventory|Where-Object repository_path -notin @($transitions.wrapper_path));Add-Check T09-NONINTERFERENCE-SET ($external.Count-eq 5-and@($external.skill_id|Sort-Object)-join','-ceq'ai-output-verifier,ai-spec-builder,ai-work-blueprint,newsletter-intelligence,vault-source-conversion') 'five additional wrappers derived from live inventory'
$fingerprint=Get-G3E2RA1R2WrapperFingerprintV2 $inventory;Add-Check T10-PER-FILE-TREE-FINGERPRINT ($fingerprint-match'^[A-F0-9]{64}$'-and$fingerprint-ceq(Get-G3E2RA1R2WrapperFingerprintV2 $inventory)) 'sorted path bytes hash fingerprint stable'

$temp=Join-Path ([IO.Path]::GetTempPath()) ('g3e2r-a1r2-'+[guid]::NewGuid().ToString('N'))
try{
    $null=[IO.Directory]::CreateDirectory($temp);$invariantRows=[Collections.Generic.List[object]]::new()
    for($i=1;$i-le 14;$i++){$invariantRows.Add([pscustomobject][ordered]@{invariant_id=('PROTECTED-{0:D2}'-f$i);state_scope='all';subject_type='file-exact';repository_path=('fixture/protected-{0:D2}.txt'-f$i);expected_fingerprint_v2='';expected_file_count='';expected_sha256=('A'*64);expected_bytes=1;mutation_policy='must-not-change';basis='protected-file'})}
    for($i=1;$i-le 3;$i++){$invariantRows.Add([pscustomobject][ordered]@{invariant_id=('SIBLING-{0:D2}'-f$i);state_scope='all';subject_type='file-exact';repository_path=('fixture/sibling-{0:D2}.txt'-f$i);expected_fingerprint_v2='';expected_file_count='';expected_sha256=('B'*64);expected_bytes=1;mutation_policy='must-not-change';basis='sibling-controller'})}
    foreach($tree in @(@('LEGACY','pre'),@('LEGACY','post'),@('LEGACY','reverse'),@('TARGET','pre'),@('TARGET','post'),@('TARGET','reverse'),@('MOS','pre'),@('MOS','post'),@('MOS','reverse'))){$invariantRows.Add([pscustomobject][ordered]@{invariant_id=('TREE-'+$tree[0]+'-'+$tree[1].ToUpperInvariant());state_scope=$tree[1];subject_type='tree-fingerprint';repository_path=('fixture/'+$tree[0].ToLowerInvariant());expected_fingerprint_v2=('C'*64);expected_file_count=1;expected_sha256='';expected_bytes='';mutation_policy='transaction-scoped';basis='transaction-tree'})}
    foreach($item in $inventory){$match=@($transitions|Where-Object wrapper_path -CEQ $item.repository_path);$id=$item.skill_id.ToUpperInvariant().Replace('-','_');if($match.Count-eq 1-and$match[0].action-ceq'transition'){$invariantRows.Add([pscustomobject][ordered]@{invariant_id="WRAPPER-$id-PRE-REVERSE";state_scope='pre-reverse';subject_type='file-exact';repository_path=$item.repository_path;expected_fingerprint_v2='';expected_file_count='';expected_sha256=$match[0].wrapper_pre_sha256;expected_bytes=$item.bytes;mutation_policy='restore-functional-prestate';basis='wrapper-full-tree'});$invariantRows.Add([pscustomobject][ordered]@{invariant_id="WRAPPER-$id-POST";state_scope='post';subject_type='file-exact';repository_path=$item.repository_path;expected_fingerprint_v2='';expected_file_count='';expected_sha256=$match[0].wrapper_post_sha256;expected_bytes=$item.bytes;mutation_policy='transaction-scoped';basis='wrapper-full-tree'})}else{$invariantRows.Add([pscustomobject][ordered]@{invariant_id="WRAPPER-$id-ALL";state_scope='all';subject_type='file-exact';repository_path=$item.repository_path;expected_fingerprint_v2='';expected_file_count='';expected_sha256=$item.sha256;expected_bytes=$item.bytes;mutation_policy='must-not-change';basis='wrapper-full-tree'})}}
    $invariantPath=Join-Path $temp 'live-invariant.csv';Save-Csv $invariantRows $invariantPath;$schema=Test-G3E2RA1R2InvariantSchema $context $invariantPath $inventory $transitions
    Add-Check T11-DERIVED-CURRENT-TOTAL ($schema.DerivedTotal-eq 52-and$schema.Rows.Count-eq(26+$inventory.Count+$actions.Count)) 'current fifty-two derived from formula'
    Add-Check T12-FIXED-14-3-9-PARTITION ($schema.Fixed.Count-eq 26-and@($schema.Fixed|Where-Object basis -CEQ 'protected-file').Count-eq 14-and@($schema.Fixed|Where-Object basis -CEQ 'sibling-controller').Count-eq 3-and@($schema.Fixed|Where-Object subject_type -CEQ 'tree-fingerprint').Count-eq 9) 'fixed invariant partition exact'
    Add-Check T13-DYNAMIC-WRAPPER-ROWS ($schema.WrapperRows.Count-eq($inventory.Count+$actions.Count)) 'one row per live wrapper plus one extra per transition'
    $pre=@($schema.Rows|Where-Object{$_.state_scope-ceq'all'-or$_.state_scope-ceq'pre'-or$_.state_scope-ceq'pre-reverse'});Add-Check T14-PRE-PROJECTION ($pre.Count-eq 36) 'twenty fixed active plus sixteen wrapper rows'
    $post=@($schema.Rows|Where-Object{$_.state_scope-ceq'all'-or$_.state_scope-ceq'post'});Add-Check T15-POST-PROJECTION ($post.Count-eq 36) 'twenty fixed active plus sixteen wrapper rows'
    $reverse=@($schema.Rows|Where-Object{$_.state_scope-ceq'all'-or$_.state_scope-ceq'reverse'-or$_.state_scope-ceq'pre-reverse'});Add-Check T16-REVERSE-PROJECTION ($reverse.Count-eq 36) 'twenty fixed active plus sixteen wrapper rows'
    $preReverse=@($schema.Rows|Where-Object state_scope -CEQ 'all');Add-Check T17-PRE-REVERSE-ADVISORY-PROJECTION ($preReverse.Count-eq 23-and$guardRaw.Contains("Unknown transition-wrapper bytes block reverse")) 'all-state twenty-three plus separate known-state participant guard'
    Add-Check T18-VIRTUAL-POST-DIFF ($schema.VirtualPostDiff.Count-eq 10-and@(Compare-Object ($schema.VirtualPostDiff|Sort-Object) ($actions.wrapper_path|Sort-Object)).Count-eq 0) 'only ten transition paths'
    Add-Check T19-TRANSITION-HASH-IDENTITIES (@($schema.WrapperRows|Where-Object state_scope -CEQ 'pre-reverse').Count-eq 10-and@($schema.WrapperRows|Where-Object state_scope -CEQ 'post').Count-eq 10) 'pre/reverse and post identities bound'
    Add-Check T20-VERIFY-ONLY-FRAMEWORK-BUILDER ($verify[0].skill_id-ceq'framework-builder'-and@($schema.WrapperRows|Where-Object repository_path -CEQ $verify[0].wrapper_path).Count-eq 1-and@($schema.WrapperRows|Where-Object repository_path -CEQ $verify[0].wrapper_path)[0].state_scope-ceq'all') 'framework-builder is exact all-state'
    Add-Check T21-EXTERNAL-WRAPPER-ALL-STATE (@($external|Where-Object{(@($schema.WrapperRows|Where-Object repository_path -CEQ $_.repository_path)).Count-ne 1}).Count-eq 0-and@($schema.WrapperRows|Where-Object{$_.repository_path-in@($external.repository_path)-and$_.state_scope-ceq'all'}).Count-eq 5) 'all five extra wrappers protected'
    $baseline=[pscustomobject][ordered]@{git_staged_count=0;root_fast_errors=0;root_fast_warnings=0;mos_passed=16;mos_total=16;mos_cleanup=$true;mos_vault_mutation='none';hard_reference_pre_paths=41;hard_reference_pre_positive=41;live_invariant_rows=$schema.DerivedTotal;wrapper_tree_files=$inventory.Count;wrapper_manifest_paths=$transitions.Count;wrapper_transition_actions=$actions.Count;wrapper_verify_only_actions=$verify.Count;wrapper_external_paths=$external.Count;wrapper_pre_fingerprint_v2=$fingerprint;residue_count=0;authority_pre='frozen'};Assert-G3E2RA1R2Baseline $context $baseline;$badBaseline=$baseline|ConvertTo-Json -Depth 5|ConvertFrom-Json;$badBaseline.wrapper_tree_files=[int]$badBaseline.wrapper_tree_files+1;Add-Check T22-DYNAMIC-BASELINE (Expect-Failure{Assert-G3E2RA1R2Baseline $context $badBaseline}) 'derived count drift fails closed'
    Add-Check T23-SEVEN-BUNDLE-CLOSURE (@($context.SealContract.required_bundle_binding_ids).Count-eq 7-and$context.SealContract.required_bundle_binding_ids-contains'G3E2R-A1R2-BUNDLE'-and$guardRaw.Contains('Seal bundle canonical path mismatch')-and$guardRaw.Contains('$manifestSpecs=')-and$guardRaw.Contains('$Seal.runtime_bindings')) 'seven canonical bundles plus transitive member and runtime locking'
    Add-Check T24-THIRTY-SIX-EXECUTIONS (@($context.SealContract.required_execution_binding_ids).Count-eq 36-and(Get-G3E2RA1R2ExecutionPaths).Count-eq 36) 'twenty-eight compatibility plus eight A1R2'
    Add-Check T25-FIFTEEN-ARTIFACTS (@($context.SealContract.required_artifact_binding_ids).Count-eq 15) 'artifact set unchanged'
    $runtime=Get-G3E2RA1R2RuntimeBindings $context $PythonExecutable;Add-Check T26-FOUR-RUNTIMES ($runtime.Count-eq 4-and@($runtime|Where-Object{$_.executable_sha256-match'^[A-F0-9]{64}$'}).Count-eq 4) 'four exact runtime identities'
    $toolText=@((Get-Content -LiteralPath (Join-Path $overlay 'tools/finalize-g3e2r-live-seal-a1r2.ps1') -Raw),(Get-Content -LiteralPath (Join-Path $overlay 'tools/invoke-g3e2-transaction-a1r2.ps1') -Raw),(Get-Content -LiteralPath (Join-Path $overlay 'tools/invoke-g3e2-reverse-a1r2.ps1') -Raw),$guardRaw)-join"`n";Add-Check T27-SIX-EXPECTED-HASH-BOUNDARIES ($toolText.Contains('Expected-A1-Hash mismatch')-and$toolText.Contains('Expected-A1R-Hash mismatch')-and$toolText.Contains('Expected-A1R2-Hash mismatch')-and$toolText.Contains('Expected-B-Hash')-and$toolText.Contains('Expected-Seal-Inputs-Hash')-and$toolText.Contains('Expected-Seal-Hash mismatch')) 'A1 A1R A1R2 B input and seal boundaries'
    Add-Check T28-TTL-INDEPENDENT-REVERSE ($context.SealContract.ttl_seconds-eq 900-and$context.SealContract.forward_requires_unexpired_seal-and$context.SealContract.reverse_ignores_expiry-and$toolText.Contains('$Use-ceq''Forward''')) 'forward TTL only and reverse expiry-independent'
    $gates=@($context.Gates);Add-Check T29-GATE-MAP-V3-SHAPE ($gates.Count-eq 40-and@($gates|Where-Object direction -CEQ 'SEAL').Count-eq 9-and@($gates|Where-Object direction -CEQ 'FWD').Count-eq 19-and@($gates|Where-Object direction -CEQ 'REV').Count-eq 12-and@($gates|Where-Object step_id -CEQ 'FWD-020').Count-eq 0) 'Gate Map v3 exact 9/19/12'
    Add-Check T30-GATE-MAP-WRAPPER-SEMANTICS (@($gates|Where-Object step_id -CEQ 'FWD-004')[0].success_contract.Contains('complete wrapper prestate')-and@($gates|Where-Object step_id -CEQ 'FWD-013')[0].success_contract.Contains('exactly ten')-and@($gates|Where-Object step_id -CEQ 'REV-007')[0].success_contract.Contains('known pre or post')) 'probe noninterference and reverse semantics explicit'
    $invFixture=Join-Path $temp 'inventory';Write-Utf8 (Join-Path $invFixture 'valid/SKILL.md') "ok`n";$valid=@(Get-G3E2RA1R2WrapperInventory $context $invFixture);Write-Utf8 (Join-Path $invFixture 'valid/extra.txt') 'x';$extraReject=Expect-Failure{Get-G3E2RA1R2WrapperInventory $context $invFixture};[IO.File]::Delete((Join-Path $invFixture 'valid/extra.txt'));Write-Utf8 (Join-Path $invFixture 'valid/nested/x.txt') 'x';$nestedReject=Expect-Failure{Get-G3E2RA1R2WrapperInventory $context $invFixture};Add-Check T31-INVENTORY-NEGATIVES ($valid.Count-eq 1-and$extraReject-and$nestedReject-and$guardRaw.Contains('ReparsePoint')) 'extra nested and reparse paths fail closed'
    $badTransition=Join-Path $temp 'bad-transition.csv';Save-Csv @($transitions|Select-Object -Skip 1) $badTransition;Add-Check T32-TRANSITION-NEGATIVES (Expect-Failure{Get-G3E2RA1R2TransitionRows $context $badTransition}) 'missing participant breaks 10/1 split'
    $badRows=@($invariantRows|Select-Object -Skip 1);$badInvariant=Join-Path $temp 'bad-invariant.csv';Save-Csv $badRows $badInvariant;Add-Check T33-INVARIANT-COUNT-NEGATIVE (Expect-Failure{Test-G3E2RA1R2InvariantSchema $context $badInvariant $inventory $transitions}) 'missing row fails dynamic formula'
    $hashRows=@($invariantRows|ForEach-Object{$_|Select-Object *});$hashRow=@($hashRows|Where-Object basis -CEQ 'wrapper-full-tree'|Select-Object -First 1)[0];$hashRow.expected_sha256='D'*64;Save-Csv $hashRows $badInvariant;Add-Check T34-WRAPPER-HASH-NEGATIVE (Expect-Failure{Test-G3E2RA1R2InvariantSchema $context $badInvariant $inventory $transitions}) 'wrong participant identity fails'
    $diffRows=@($invariantRows|ForEach-Object{$_|Select-Object *});$extraRow=@($diffRows|Where-Object{$_.basis-ceq'wrapper-full-tree'-and$_.state_scope-ceq'all'}|Select-Object -First 1)[0];$extraRow.state_scope='post';Save-Csv $diffRows $badInvariant;Add-Check T35-VIRTUAL-DIFF-NEGATIVE (Expect-Failure{Test-G3E2RA1R2InvariantSchema $context $badInvariant $inventory $transitions}) 'nonparticipant post-only rewrite fails'
    Add-Check T36-B-COMPATIBILITY-CONTRACT ($context.BContract.bound_member_count-eq 18-and$context.BContract.prepared_file_count-eq 19-and$context.BContract.sealed_file_count-eq 20-and-not(Test-Path -LiteralPath (Resolve-G3E2RA1R2InRoot $root ([string]$context.BContract.canonical_root))) ) 'B contract reused transitively and live B absent'
    $guard=Join-Path $overlay 'tools/g3e2r-a1r2-guard-lib.psm1';$finalizer=Join-Path $overlay 'tools/finalize-g3e2r-live-seal-a1r2.ps1';$forward=Join-Path $overlay 'tools/invoke-g3e2-transaction-a1r2.ps1';$reverseTool=Join-Path $overlay 'tools/invoke-g3e2-reverse-a1r2.ps1';$parseOk=@(Parse-Tool $guard).Count-eq 0-and@(Parse-Tool $finalizer).Count-eq 0-and@(Parse-Tool $forward).Count-eq 0-and@(Parse-Tool $reverseTool).Count-eq 0-and@(Parse-Tool $PSCommandPath).Count-eq 0;$common=@('-VaultRoot',$root,'-OverlayRoot',$overlay,'-ExpectedA1Hash',$expectedA1,'-ExpectedA1RHash',$expectedA1R,'-ExpectedA1R2Hash',$expectedA1R2,'-Json');$fv=Invoke-JsonScript $finalizer (@('-Mode','Validate')+$common);$fwv=Invoke-JsonScript $forward (@('-Mode','Validate')+$common);$rv=Invoke-JsonScript $reverseTool (@('-Mode','Validate')+$common);Add-Check T37-PARSE-AND-VALIDATE ($parseOk-and$fv.verdict-ceq'PASS'-and$fwv.verdict-ceq'PASS'-and$rv.verdict-ceq'PASS') 'five scripts parse and three entrypoints validate read-only'
    $pre=Invoke-JsonScript $forward (@('-Mode','Simulate','-FailAtStep','FWD-009')+$common);$postFailure=Invoke-JsonScript $forward (@('-Mode','Simulate','-FailAtStep','FWD-010')+$common);$revSim=Invoke-JsonScript $reverseTool (@('-Mode','Simulate')+$common);Add-Check T38-SIMULATION-BOUNDARIES ($pre.verdict-ceq'HOLD_NO_MUTATION'-and-not$pre.reverse_invoked-and$postFailure.verdict-ceq'REVERSED_ROUTING_FROZEN'-and$postFailure.reverse_invoked-and@($revSim.completed).Count-eq 12) 'pre holds and post invokes full reverse'
    $a1rTest=Join-Path $context.A1RRoot 'tools/test-g3e2r-a1r-bundle.ps1';$a1rResult=Invoke-JsonScript $a1rTest @('-VaultRoot',$root,'-OverlayRoot',$context.A1RRoot,'-PythonExecutable',$PythonExecutable,'-Json');Add-Check T39-UPSTREAM-REGRESSIONS ($a1rResult.verdict-ceq'PASS'-and$a1rResult.groups-eq 34-and@($a1rResult.checks|Where-Object{$_-like'T33-UPSTREAM-A1-REGRESSION*'}).Count-eq 1) 'unchanged A1R 34/34 includes unchanged A1 27/27'
}
finally{if(Test-Path -LiteralPath $temp){Remove-Item -LiteralPath $temp -Recurse -Force}}

$rootFast=&$powerShell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $root 'tools/test-wiki-integrity.ps1') -Profile Fast 2>&1;if($LASTEXITCODE-ne 0){throw "Root Fast failed: $($rootFast-join[Environment]::NewLine)"};$mos=&$powerShell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $root 'projects/marketing-operating-system/tools/test-federation-contracts.ps1') 2>&1;if($LASTEXITCODE-ne 0){throw "MOS failed: $($mos-join[Environment]::NewLine)"}
$git=[string]((Get-Command git -CommandType Application|Select-Object -First 1).Source);Assert-G3E2RA1R2GitStagingEmpty $root $git;Assert-G3E2RA1R2NoResidue $root;$unchanged=(Get-G3E2RA1R2TreeFingerprintV2 $context.A1RRoot)-ceq$a1rBefore-and(Get-G3E2RA1R2TreeFingerprintV2 $context.A1RContext.A1Root)-ceq$a1Before-and(Get-G3E2RA1R2TreeFingerprintV2 $context.A1RContext.A1Context.ARoot)-ceq$aBefore-and(Get-G3E2RA1R2TreeFingerprintV2 $context.A1RContext.A1Context.G3E1Root)-ceq$g3e1Before;$rootGreen=($rootFast-join"`n")-match'(?im)0\s+errors?'-and($rootFast-join"`n")-match'(?im)0\s+warnings?';$mosGreen=($mos-join"`n")-match'(?im)16/16';$bAbsent=-not(Test-Path -LiteralPath (Resolve-G3E2RA1R2InRoot $root ([string]$context.BContract.canonical_root)))
Add-Check T40-LIVE-REGRESSION-AND-SCOPE ($rootGreen-and$mosGreen-and$unchanged-and$bAbsent-and@($checks).Count-eq 39-and-not(Test-Path -LiteralPath (Join-Path $temp 'anything'))) 'Root 0/0 MOS 16/16 upstreams exact staging residue zero B absent routing frozen'
$result=[ordered]@{contract='g3e2r-a1r2-test/v1';verdict='PASS';groups=$checks.Count;expected_a1_hash=$expectedA1;expected_a1r_hash=$expectedA1R;expected_a1r2_hash=$expectedA1R2;wrapper_files=$inventory.Count;transition_actions=$actions.Count;verify_only_actions=$verify.Count;external_wrappers=$external.Count;derived_invariant_rows=$schema.DerivedTotal;checks=@($checks);temporary_fixture_removed=(-not(Test-Path -LiteralPath $temp));live_mutation='none';live_capability_probe='not-run';b_candidate='absent';routing_state='frozen';git_staging='empty'}
if($Json){$result|ConvertTo-Json -Depth 8 -Compress}else{Write-Output "PASS | $($checks.Count)/40 A1R2 groups | A1R 34/34 | A1 27/27 | static and temporary-only | routing frozen"}
